dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    api("cn.hutool:hutool-core:5.7.14")
    api("commons-io:commons-io:2.6")
    api("commons-codec:commons-codec:1.15")
    api("com.google.guava:guava:30.0-jre")
    api("org.bouncycastle:bcprov-jdk15on:1.64")
    api("org.hashids:hashids:1.0.3")
    // api("org.apache.httpcomponents:httpmime:4.5.13")
    api("org.slf4j:slf4j-api:1.7.30")
    api("org.springframework:spring-web")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    api("com.github.ben-manes.caffeine:caffeine:2.8.8")
    api("com.squareup.okhttp3:okhttp:4.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.6.3")
}
